### PR TITLE
export include directories

### PR DESCRIPTION
**Pull request by Karsten1987**
connects to https://github.com/stonier/ecl_core/pull/86

### CODE REVIEW

**Comment by stonier** [comment]
Wondering why the exported include directories? You get them for free in the interfaces when you do, e.g.

```
target_link_libraries(${MY_TARGET}
  ecl_time_lite::ecl_time_lite
)
```

**Comment by Karsten1987** [comment]
The same updates as in https://github.com/stonier/ecl_core/pull/86#issuecomment-520537614 have been made for this repo.

**Comment by stonier** [comment]
@Karsten1987 how did you have these fixes showing up as errors? I've got `-Werror` and `-Wpedantic` enabled on bionic now and not having any issues without the fixes you have diff'd here.

**Comment by Karsten1987** [comment]
The unused variable warning comes while compiling `ecl_errors`:
```
--- stderr: ecl_errors
/Users/karsten/workspace/bosch/kobuki_ws/src/stonier/ecl_lite/ecl_errors/src/examples/errors.cpp:29:3: error: unused typedef 'compile_time_check29' [-Werror,-Wunused-local-typedef]
                ecl_compile_time_assert( M >= 0 );
                ^
/Users/karsten/workspace/bosch/kobuki_ws/src/stonier/ecl_lite/ecl_errors/src/examples/../../include/ecl/errors/compile_time_assert.hpp:61:112: note: expanded from macro 'ecl_compile_time_assert'
   typedef ecl::static_assert_test<sizeof(ecl::COMPILE_TIME_FAILURE< static_cast<bool>(logical_expression) >)> JOIN(compile_time_check,__LINE__)
                                                                                                               ^
/Users/karsten/workspace/bosch/kobuki_ws/src/stonier/ecl_lite/ecl_errors/src/examples/../../include/ecl/errors/macros.hpp:55:22: note: expanded from macro 'JOIN'
#define JOIN( X, Y ) DO_JOIN( X, Y )
                     ^
/Users/karsten/workspace/bosch/kobuki_ws/src/stonier/ecl_lite/ecl_errors/src/examples/../../include/ecl/errors/macros.hpp:56:25: note: expanded from macro 'DO_JOIN'
#define DO_JOIN( X, Y ) DO_JOIN2(X,Y)
                        ^
/Users/karsten/workspace/bosch/kobuki_ws/src/stonier/ecl_lite/ecl_errors/src/examples/../../include/ecl/errors/macros.hpp:57:26: note: expanded from macro 'DO_JOIN2'
#define DO_JOIN2( X, Y ) X##Y
                         ^
<scratch space>:287:1: note: expanded from here
compile_time_check29
^
/Users/karsten/workspace/bosch/kobuki_ws/src/stonier/ecl_lite/ecl_errors/src/examples/errors.cpp:30:3: error: unused typedef 'compile_time_check30' [-Werror,-Wunused-local-typedef]
                ecl_compile_time_assert( N >= 0 );
                ^
/Users/karsten/workspace/bosch/kobuki_ws/src/stonier/ecl_lite/ecl_errors/src/examples/../../include/ecl/errors/compile_time_assert.hpp:61:112: note: expanded from macro 'ecl_compile_time_assert'
   typedef ecl::static_assert_test<sizeof(ecl::COMPILE_TIME_FAILURE< static_cast<bool>(logical_expression) >)> JOIN(compile_time_check,__LINE__)
                                                                                                               ^
/Users/karsten/workspace/bosch/kobuki_ws/src/stonier/ecl_lite/ecl_errors/src/examples/../../include/ecl/errors/macros.hpp:55:22: note: expanded from macro 'JOIN'
#define JOIN( X, Y ) DO_JOIN( X, Y )
                     ^
/Users/karsten/workspace/bosch/kobuki_ws/src/stonier/ecl_lite/ecl_errors/src/examples/../../include/ecl/errors/macros.hpp:56:25: note: expanded from macro 'DO_JOIN'
#define DO_JOIN( X, Y ) DO_JOIN2(X,Y)
                        ^
/Users/karsten/workspace/bosch/kobuki_ws/src/stonier/ecl_lite/ecl_errors/src/examples/../../include/ecl/errors/macros.hpp:57:26: note: expanded from macro 'DO_JOIN2'
#define DO_JOIN2( X, Y ) X##Y
                         ^
<scratch space>:289:1: note: expanded from here
compile_time_check30
^
2 errors generated.
```
 
The `const` incorrectness comes when compiling `ecl_time_lite`:
```
--- stderr: ecl_time_lite
In file included from /Users/karsten/workspace/bosch/kobuki_ws/src/stonier/ecl_lite/ecl_time_lite/src/lib/cpu_time.cpp:12:
In file included from /Users/karsten/workspace/bosch/kobuki_ws/src/stonier/ecl_lite/ecl_time_lite/src/lib/../../include/ecl/time_lite/cpu_time.hpp:19:
/Users/karsten/workspace/bosch/kobuki_ws/src/stonier/ecl_lite/ecl_time_lite/src/lib/../../include/ecl/time_lite/errors.hpp:44:23: error: 'ecl::TimeError::outOfRangeErrorString' hides overloaded virtual function [-Werror,-Woverloaded-virtual]
  virtual const char* outOfRangeErrorString() { return "The input time sec/nsec pair was outside of the permitted range."; }
                      ^
/Users/karsten/workspace/bosch/kobuki_ws/install/ecl_errors/include/ecl/errors/handlers.hpp:145:22: note: hidden overloaded virtual function 'ecl::Error::outOfRangeErrorString' declared here: different qualifiers (const vs none)
        virtual const char* outOfRangeErrorString() const { return "Out of range error - tried to access beyond the range of the object (usually container)."; }
                            ^
In file included from /Users/karsten/workspace/bosch/kobuki_ws/src/stonier/ecl_lite/ecl_time_lite/src/lib/cpu_time.cpp:12:
In file included from /Users/karsten/workspace/bosch/kobuki_ws/src/stonier/ecl_lite/ecl_time_lite/src/lib/../../include/ecl/time_lite/cpu_time.hpp:19:
/Users/karsten/workspace/bosch/kobuki_ws/src/stonier/ecl_lite/ecl_time_lite/src/lib/../../include/ecl/time_lite/errors.hpp:45:23: error: 'ecl::TimeError::argNotSupportedErrorString' hides overloaded virtual function [-Werror,-Woverloaded-virtual]
  virtual const char* argNotSupportedErrorString() { return "The clock specified is not supported on this system."; }
                      ^
/Users/karsten/workspace/bosch/kobuki_ws/install/ecl_errors/include/ecl/errors/handlers.hpp:161:22: note: hidden overloaded virtual function 'ecl::Error::argNotSupportedErrorString' declared here: different qualifiers (const vs none)
        virtual const char* argNotSupportedErrorString() const { return "The combination of input arguments is not supported on this platform."; }
                            ^
In file included from /Users/karsten/workspace/bosch/kobuki_ws/src/stonier/ecl_lite/ecl_time_lite/src/lib/cpu_time.cpp:12:
In file included from /Users/karsten/workspace/bosch/kobuki_ws/src/stonier/ecl_lite/ecl_time_lite/src/lib/../../include/ecl/time_lite/cpu_time.hpp:19:
/Users/karsten/workspace/bosch/kobuki_ws/src/stonier/ecl_lite/ecl_time_lite/src/lib/../../include/ecl/time_lite/errors.hpp:46:23: error: 'ecl::TimeError::permissionsErrorString' hides overloaded virtual function [-Werror,-Woverloaded-virtual]
  virtual const char* permissionsErrorString() { return "You do not have permission to set the specified clock."; }
                      ^
/Users/karsten/workspace/bosch/kobuki_ws/install/ecl_errors/include/ecl/errors/handlers.hpp:157:22: note: hidden overloaded virtual function 'ecl::Error::permissionsErrorString' declared here: different qualifiers (const vs none)
        virtual const char* permissionsErrorString() const { return "The caller does not have the required permissions."; }
                            ^
In file included from /Users/karsten/workspace/bosch/kobuki_ws/src/stonier/ecl_lite/ecl_time_lite/src/lib/cpu_time.cpp:12:
In file included from /Users/karsten/workspace/bosch/kobuki_ws/src/stonier/ecl_lite/ecl_time_lite/src/lib/../../include/ecl/time_lite/cpu_time.hpp:19:
/Users/karsten/workspace/bosch/kobuki_ws/src/stonier/ecl_lite/ecl_time_lite/src/lib/../../include/ecl/time_lite/errors.hpp:47:23: error: 'ecl::TimeError::memoryErrorString' hides overloaded virtual function [-Werror,-Woverloaded-virtual]
  virtual const char* memoryErrorString() { return "One of the input arguments is not in memory addressable space."; }
                      ^
/Users/karsten/workspace/bosch/kobuki_ws/install/ecl_errors/include/ecl/errors/handlers.hpp:158:22: note: hidden overloaded virtual function 'ecl::Error::memoryErrorString' declared here: different qualifiers (const vs none)
        virtual const char* memoryErrorString() const { return "There was a problem allocating the requested memory."; }
                            ^
In file included from /Users/karsten/workspace/bosch/kobuki_ws/src/stonier/ecl_lite/ecl_time_lite/src/lib/cpu_time.cpp:12:
In file included from /Users/karsten/workspace/bosch/kobuki_ws/src/stonier/ecl_lite/ecl_time_lite/src/lib/../../include/ecl/time_lite/cpu_time.hpp:19:
/Users/karsten/workspace/bosch/kobuki_ws/src/stonier/ecl_lite/ecl_time_lite/src/lib/../../include/ecl/time_lite/errors.hpp:48:23: error: 'ecl::TimeError::interruptedErrorString' hides overloaded virtual function [-Werror,-Woverloaded-virtual]
  virtual const char* interruptedErrorString() { return "This operation was interrupted by a signal."; }
                      ^
/Users/karsten/workspace/bosch/kobuki_ws/install/ecl_errors/include/ecl/errors/handlers.hpp:165:22: note: hidden overloaded virtual function 'ecl::Error::interruptedErrorString' declared here: different qualifiers (const vs none)
        virtual const char* interruptedErrorString() const { return "This operation was interrupted."; }
                            ^
```

 I am using clang on OSX Mojave.

**Comment by stonier** [comment]
Cherry-picked the warning fixes in #30. The export includes will be left off, kobuki_core will make direct use of `target_link_libraries` once we get there.

Releasing in `v1.0.3`

Thanks!

**Pull request closed without merging**
